// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeHTML(arg1) {
  return window['go']['main']['App']['AnalyzeHTML'](arg1);
}

export function AnalyzeSource(arg1) {
  return window['go']['main']['App']['AnalyzeSource'](arg1);
}

export function AppendLog(arg1) {
  return window['go']['main']['App']['AppendLog'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelShutdown() {
  return window['go']['main']['App']['CancelShutdown']();
}

export function ChooseFFmpeg() {
  return window['go']['main']['App']['ChooseFFmpeg']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetSavedSession() {
  return window['go']['main']['App']['GetSavedSession']();
}

export function GetShutdownStatus() {
  return window['go']['main']['App']['GetShutdownStatus']();
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function NewLogSession() {
  return window['go']['main']['App']['NewLogSession']();
}

export function OpenHTMLFile() {
  return window['go']['main']['App']['OpenHTMLFile']();
}

export function PauseDownload() {
  return window['go']['main']['App']['PauseDownload']();
}

export function RememberOutputDirectory(arg1) {
  return window['go']['main']['App']['RememberOutputDirectory'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SaveLog(arg1) {
  return window['go']['main']['App']['SaveLog'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function ScheduleShutdown(arg1) {
  return window['go']['main']['App']['ScheduleShutdown'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
