// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCookieFile() {
  return window['go']['main']['App']['AddCookieFile']();
}

export function AnalyzeHTML(arg1) {
  return window['go']['main']['App']['AnalyzeHTML'](arg1);
}

export function AnalyzeSource(arg1) {
  return window['go']['main']['App']['AnalyzeSource'](arg1);
}

export function AppendLog(arg1) {
  return window['go']['main']['App']['AppendLog'](arg1);
}

export function CancelAnalyze() {
  return window['go']['main']['App']['CancelAnalyze']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelShutdown() {
  return window['go']['main']['App']['CancelShutdown']();
}

export function CheckYtDlpPlugins(arg1) {
  return window['go']['main']['App']['CheckYtDlpPlugins'](arg1);
}

export function ChooseFFmpeg() {
  return window['go']['main']['App']['ChooseFFmpeg']();
}

export function ClearCookies() {
  return window['go']['main']['App']['ClearCookies']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function EnsureYtDlpFresh() {
  return window['go']['main']['App']['EnsureYtDlpFresh']();
}

export function GetCookieStatus() {
  return window['go']['main']['App']['GetCookieStatus']();
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetProviderStatus() {
  return window['go']['main']['App']['GetProviderStatus']();
}

export function GetSavedSession() {
  return window['go']['main']['App']['GetSavedSession']();
}

export function GetShutdownStatus() {
  return window['go']['main']['App']['GetShutdownStatus']();
}

export function GetYtDlpStatus() {
  return window['go']['main']['App']['GetYtDlpStatus']();
}

export function GetYtDlpTuning() {
  return window['go']['main']['App']['GetYtDlpTuning']();
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function InstallPOTokenProvider() {
  return window['go']['main']['App']['InstallPOTokenProvider']();
}

export function InstallYtDlp() {
  return window['go']['main']['App']['InstallYtDlp']();
}

export function NewLogSession() {
  return window['go']['main']['App']['NewLogSession']();
}

export function OpenHTMLFile() {
  return window['go']['main']['App']['OpenHTMLFile']();
}

export function PauseDownload() {
  return window['go']['main']['App']['PauseDownload']();
}

export function RefreshYouTubeSession() {
  return window['go']['main']['App']['RefreshYouTubeSession']();
}

export function RememberCookieSource(arg1) {
  return window['go']['main']['App']['RememberCookieSource'](arg1);
}

export function RememberMaxHeight(arg1) {
  return window['go']['main']['App']['RememberMaxHeight'](arg1);
}

export function RememberOutputDirectory(arg1) {
  return window['go']['main']['App']['RememberOutputDirectory'](arg1);
}

export function RememberYtDlpTuning(arg1) {
  return window['go']['main']['App']['RememberYtDlpTuning'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SaveLog(arg1) {
  return window['go']['main']['App']['SaveLog'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function ScheduleShutdown(arg1) {
  return window['go']['main']['App']['ScheduleShutdown'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectPluginDir() {
  return window['go']['main']['App']['SelectPluginDir']();
}

export function SetProgressIndicator(arg1, arg2) {
  return window['go']['main']['App']['SetProgressIndicator'](arg1, arg2);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartPOTokenProvider(arg1) {
  return window['go']['main']['App']['StartPOTokenProvider'](arg1);
}

export function StopPOTokenProvider() {
  return window['go']['main']['App']['StopPOTokenProvider']();
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}
