// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCookieFile():Promise<main.CookieStatus>;

export function AnalyzeHTML(arg1:string):Promise<main.AnalysisResult>;

export function AnalyzeSource(arg1:string):Promise<main.AnalysisResult>;

export function AppendLog(arg1:string):Promise<string>;

export function CancelAnalyze():Promise<void>;

export function CancelDownload():Promise<void>;

export function CancelShutdown():Promise<main.ShutdownStatus>;

export function CheckYtDlpPlugins(arg1:string):Promise<main.PluginCheck>;

export function ChooseFFmpeg():Promise<main.FFmpegStatus>;

export function ClearCookies():Promise<void>;

export function ClearSession():Promise<void>;

export function EnsureYtDlpFresh():Promise<main.ToolStatus>;

export function GetCookieStatus():Promise<main.CookieStatus>;

export function GetFFmpegStatus():Promise<main.FFmpegStatus>;

export function GetInitialState():Promise<main.InitialState>;

export function GetLogPath():Promise<string>;

export function GetProviderStatus():Promise<main.ProviderStatus>;

export function GetSavedSession():Promise<main.SavedSession>;

export function GetShutdownStatus():Promise<main.ShutdownStatus>;

export function GetYtDlpStatus():Promise<main.ToolStatus>;

export function GetYtDlpTuning():Promise<main.YtDlpTuning>;

export function InstallFFmpeg():Promise<main.FFmpegStatus>;

export function InstallPOTokenProvider():Promise<main.ProviderStatus>;

export function InstallYtDlp():Promise<main.ToolStatus>;

export function NewLogSession():Promise<string>;

export function OpenHTMLFile():Promise<main.SourceDocument>;

export function PauseDownload():Promise<main.DownloadControlStatus>;

export function RefreshYouTubeSession():Promise<void>;

export function RememberCookieSource(arg1:string):Promise<void>;

export function RememberMaxHeight(arg1:number):Promise<void>;

export function RememberOutputDirectory(arg1:string):Promise<void>;

export function RememberYtDlpTuning(arg1:main.YtDlpTuning):Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveLog(arg1:string):Promise<string>;

export function SaveSession(arg1:main.SessionState):Promise<void>;

export function ScheduleShutdown(arg1:number):Promise<main.ShutdownStatus>;

export function SelectOutputDirectory():Promise<string>;

export function SelectPluginDir():Promise<main.YtDlpTuning>;

export function SetProgressIndicator(arg1:number,arg2:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartDownload(arg1:main.DownloadRequest):Promise<void>;

export function StartPOTokenProvider(arg1:number):Promise<main.ProviderStatus>;

export function StopPOTokenProvider():Promise<main.ProviderStatus>;

export function UpdateYtDlp():Promise<main.ToolStatus>;
