// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeHTML(arg1) {
  return window['go']['main']['App']['AnalyzeHTML'](arg1);
}

export function AnalyzeSource(arg1) {
  return window['go']['main']['App']['AnalyzeSource'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ChooseFFmpeg() {
  return window['go']['main']['App']['ChooseFFmpeg']();
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function OpenHTMLFile() {
  return window['go']['main']['App']['OpenHTMLFile']();
}

export function RememberOutputDirectory(arg1) {
  return window['go']['main']['App']['RememberOutputDirectory'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
