// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeHTML(arg1:string):Promise<main.AnalysisResult>;

export function AnalyzeSource(arg1:string):Promise<main.AnalysisResult>;

export function CancelDownload():Promise<void>;

export function ChooseFFmpeg():Promise<main.FFmpegStatus>;

export function GetFFmpegStatus():Promise<main.FFmpegStatus>;

export function GetInitialState():Promise<main.InitialState>;

export function InstallFFmpeg():Promise<main.FFmpegStatus>;

export function OpenHTMLFile():Promise<main.SourceDocument>;

export function RememberOutputDirectory(arg1:string):Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function SelectOutputDirectory():Promise<string>;

export function StartDownload(arg1:main.DownloadRequest):Promise<void>;
